sudo: required

dist: focal

services:
  - docker

env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1

before_install:
  - openssl aes-256-cbc -K $encrypted_1234567890abcdef_key -iv $encrypted_1234567890abcdef_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project fibonacci-sequence-k8s
  - gcloud config set compute/zone us-east1-b
  - gcloud container clusters get-credentials fs-cluster

  # Login in to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

  - docker build -t lingfungc/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true lingfungc/react-test npm test

deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: master
